apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rancher-csp-billing-adapter.fullname" . }}-post-delete
  annotations:
    meta.helm.sh/release-name: {{ include "rancher-csp-billing-adapter.fullname" . }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
rules:
- apiGroups: [ "*" ]
  resources: [ "*" ]
  verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rancher-csp-billing-adapter.fullname" . }}-post-delete
  annotations:
    meta.helm.sh/release-name: {{ include "rancher-csp-billing-adapter.fullname" . }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "6"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rancher-csp-billing-adapter.fullname" . }}-post-delete
subjects:
  - kind: ServiceAccount
    name: {{ include "rancher-csp-billing-adapter.fullname" . }}-post-delete
    namespace: {{ .Release.Namespace }}
