apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rancher-csp-billing-adapter.fullname" . }}-pre-install
  labels: 
    {{- include "rancher-csp-billing-adapter.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ include "rancher-csp-billing-adapter.fullname" . }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "rancher-csp-billing-adapter.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "rancher-csp-billing-adapter.serviceAccountName" . }}-pre-install
      containers:
        - name: {{ include "rancher-csp-billing-adapter.fullname" . }}-pre-install
          image: "rancher/shell:v0.1.20" 
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          command:
            - /scripts/pre-install-hook.sh
          volumeMounts:
            - mountPath: /scripts
              name: config-volume
          env:
            - name: RANCHER_NAMESPACE
              value: {{ .Values.rancher.namespace }} 
            - name: RANCHER_HOSTNAME
              value: {{ .Values.rancher.hostname }} 
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "rancher-csp-billing-adapter.fullname" . }}-pre-install
            defaultMode: 0755
