apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-cluster-role
rules:
- apiGroups:
  - {{ template "csp-billing-adapter.usageAPIGroup" }}
  resources:
  - {{ template "csp-billing-adapter.usageCRDPlural" }}
  resourceNames:
  - {{ template "csp-billing-adapter.usageResource" }}
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "rancher-csp-billing-adapter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-configmap-reader-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - csp-adapter-cache
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - csp-config
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-configmap-reader-role
subjects:
  - kind: ServiceAccount
    name: {{ include "rancher-csp-billing-adapter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
