apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rancher-csp-billing-adapter.serviceAccountName" . }}
  labels:
    {{- include "rancher-csp-billing-adapter.labels" . | nindent 4 }}
  namespace: cattle-csp-billing-adapter-system
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
