apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: cattle-csp-usage-operator-system
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - env:
        - name: CATTLE_DEBUG
          value: {{ .Values.debug | quote }}
        - name: CATTLE_DEV_MODE
          value: {{ .Values.devMode | quote }}
        - name: K8S_OUTPUT_CONFIGMAP
          value: '{{ template "csp-usage-operator.outputConfigMap"  }}'
        - name: K8S_OUTPUT_NOTIFICATION
          value: '{{ template "csp-usage-operator.outputNotification" }}'
        - name: K8S_CACHE_SECRET
          value: '{{ template "csp-usage-operator.cacheSecret"  }}'
        - name: K8S_HOSTNAME_SETTING
          value: '{{ template "csp-usage-operator.hostnameSetting"  }}'
        - name: K8S_RANCHER_VERSION_SETTING
          value: '{{ template "csp-usage-operator.versionSetting"  }}'
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        name: {{ .Chart.Name }}
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
{{- if .Values.additionalTrustedCAs }}
        volumeMounts:
          - mountPath: /etc/ssl/certs/rancher-cert.pem
            name: tls-ca-volume
            subPath: ca-additional.pem
            readOnly: true
{{- end }}
      serviceAccountName: {{ .Chart.Name }}
{{- if .Values.additionalTrustedCAs }}
      volumes:
        - name: tls-ca-volume
          secret:
            defaultMode: 0444
            secretName: tls-ca-additional
{{- end }}
