apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
 name: rancherusagerecords.rancher.com
spec:
 group: rancher.com
 names:
   plural: rancherusagerecords
   singular: rancherusagerecord
   kind: RancherUsageRecord
   shortNames:
   - rur
 scope: Cluster
 versions:
   - name: v1
     served: true
     storage: true
     schema:
       openAPIV3Schema:
         type: object
         properties:
           base_product:
             type: string
           managed_node_count:
             type: integer
           reporting_time:
             type: string
         required:
         - managed_node_count
         - reporting_time
         - base_product
