rancherBillingAdapterImage: registry.opensuse.org/home/yeey/rancher-csp-billing-adapter/containers/rancher-local-billing-container
rancherBillingAdapterImageTag: latest
#rancherBillingAdapterImageDigest: sha256:...
#rancherBillingAdapterImagePullPolicy: Always

imagePullSecrets: []

serviceAccount:
  # Annotations to add to the service account
  annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
