image:
  repository: registry.opensuse.org/home/yeey/rancher-csp-billing-adapter/containers/rancher-local-billing-container
  tag: latest
  imagePullPolicy: Always

imagePullSecrets: []

serviceAccount:
  # Annotations to add to the service account
  annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
