debug: true
# used for development only - not supported in production
devMode: true

rancherUsageOperatorImage: yeey/csp-rancher-usage-operator
rancherUsageOperatorImageTag: latest
#rancherUsageOperatorImageDigest: sha256:...
#rancherUsageOperatorImagePullPolicy: Always

serviceAccount:
  annotations: []

nodeSelector: {}

tolerations: []

affinity: {}

# if rancher is using a privateCA, this certificate must be provided as a secret in the adapter's namespace - see the
# readme/docs for more details
additionalTrustedCAs: true
rancherImage: rancher/rancher
rancherImageTag: v2.7.3
