apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csp-rancher-usage-operator.fullname" . }}
  labels:
    {{- include "csp-rancher-usage-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "csp-rancher-usage-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "csp-rancher-usage-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.additionalTrustedCAs }}
      initContainers:
      - name: init-usage-operator
{{- if .Values.rancherImageDigest }}
        image: {{ .Values.rancherImage }}@{{ .Values.rancherImageDigest }}
{{- else }}
        image: {{ .Values.rancherImage }}:{{ default .Chart.AppVersion .Values.rancherImageTag }}
{{- end }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.rancherImagePullPolicy }}
        command: ["/bin/sh"]
        args: ["-c",'kubectl exec svc/rancher -n cattle-system -- kubectl get secret tls-rancher -n cattle-system -o jsonpath="{.data.tls\\.crt}" | base64 -d > /tlsvol/ca-additional.pem']
        volumeMounts:
        - name: tls-ca-volume
          mountPath: "/tlsvol/"
{{- end }}       
      containers:
      - env:
        - name: CATTLE_DEBUG
          value: {{ .Values.debug | quote }}
        - name: K8S_CSP_BILLING_ADAPTER_NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: K8S_CSP_BILLING_ADAPTER_CONFIGMAP
          value: '{{ include "csp-usage-operator.cspBillingAdapterConfigMap" . }}'
        - name: K8S_CSP_BILLING_NO_BILL_THRESHOLD
          value: '{{ include "csp-usage-operator.cspBillingNoBillThreshold" . }}'
        - name: K8S_CSP_BILLING_MANAGER_INTERVAL
          value: '{{ include "csp-usage-operator.cspBillingManagerInterval" . }}'
        - name: K8S_OUTPUT_NOTIFICATION
          value: '{{ include "csp-usage-operator.outputNotification" . }}'
        - name: K8S_HOSTNAME_SETTING
          value: '{{ include "csp-usage-operator.hostnameSetting"  . }}'
        - name: K8S_RANCHER_VERSION_SETTING
          value: '{{ include "csp-usage-operator.versionSetting"  . }}'
{{- if .Values.rancherUsageOperatorImageDigest }}
        image: {{ .Values.rancherUsageOperatorImage }}@{{ .Values.rancherUsageOperatorImageDigest }}
{{- else }}
        image: {{ .Values.rancherUsageOperatorImage }}:{{ default .Chart.AppVersion .Values.rancherUsageOperatorImageTag }}
{{- end }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.rancherUsageOperatorImagePullPolicy }}
        name: {{ .Chart.Name }}
{{- if .Values.additionalTrustedCAs }}
        volumeMounts:
          - mountPath: /etc/ssl/certs/rancher-cert.pem
            name: tls-ca-volume
            subPath: ca-additional.pem
            readOnly: true
{{- end }}
      serviceAccountName: {{ include "csp-rancher-usage-operator.serviceAccountName" . }}
{{- if .Values.additionalTrustedCAs }}
      volumes:
      - name: tls-ca-volume
        emptyDir: {}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
