apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-cluster-role
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - ranchermetrics
  verbs:
  - get
- apiGroups:
  - management.cattle.io
  resources:
  - rancherusernotifications
  resourceNames:
  - {{ template "csp-usage-operator.outputNotification" }}
  verbs:
  - "*"
- apiGroups:
  - management.cattle.io
  resources:
  - rancherusernotifications
  verbs:
  - create
- apiGroups:
  - management.cattle.io
  resources:
  - settings
  resourceNames:
  - {{ template "csp-usage-operator.hostnameSetting"  }}
  - {{ template "csp-usage-operator.versionSetting"  }}
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - susecloud.net
  resources:
  - cspadapterusagerecords
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "csp-rancher-usage-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-configmap-reader-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - {{ template "csp-usage-operator.cspBillingAdapterConfigMap"  }}
  verbs:
  - get
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-configmap-reader-role
subjects:
  - kind: ServiceAccount
    name: {{ include "csp-rancher-usage-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
